baseURL = "https://Qc-qi.github.io/qc/"
locale = "zh-CN"
title = "我的博客"
theme = "PaperMod"
contentDir = "content"

[params]
  description = "个人技术博客"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  disableSpecialistPost = true
  searchHidden = false

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Qc-qi"

[[params.socialIcons]]
  name = "email"
  url = "mailto:3371219632@qq.com"