baseURL = "https://Qc-qi.github.io/qc/"
languageCode = "zh-cn"
title = "我的博客"
theme = "PaperMod"

menu:
  main:
    - identifier: home
      name: 首页
      url: /
      weight: 1
    - identifier: posts
      name: 文章
      url: /posts/
      weight: 2
    - identifier: search
      name: 搜索
      url: /search/
      weight: 3

[params]
  description = "个人技术博客"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  disableSpecialistPost = true
  searchHidden = false

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Qc-qi"

[[params.socialIcons]]
  name = "email"
  url = "mailto:3371219632@qq.com"